### ISSUE TITLE
container csanchez/jenkins-swarm:1.609.2 fails to start in AWS

### ISSUE THREAD

**Issue by ipedrazas** [carlossg/kubernetes-jenkins#2]
This configuration doesn't seem to work when running k8s in AWS

```
        volumeMounts: 
          - 
            name: "jenkins-data"
            mountPath: "/var/jenkins_home"
    volumes: 
      - 
        name: "jenkins-data"
        hostPath: 
          path: "/home/docker/jenkins"
```

This is the logs of the pod:

-> % kubectl logs jenkins
/usr/local/bin/jenkins.sh: line 25: /var/jenkins_home/copy_reference_file.log: Permission denied
